travis:
  secure:
    BINSTAR_TOKEN: F2i+9RBS2FzSsng1SX2UA5QBstfKO8Yfsn1HL+nzxaC/ATAhnHvtt1Dz9XsG9r8kkBXuBQgAkPnW0DxxzxQj5FO48/9onEQOQZ414tPLj+F7Pv2mVCtusIbnihBIXeZnU9IL7pBQZJ+yv98nJKu5j0jZhBfnp99dJxv/eUPKpJPj9Ew3kj6KIF7tbcOHdQKSO8PTkKX3eChvvUs0NpGDkZUqpcEtT92jX6/vZeYFK8Hh2BYP09Mgoy8+X+F5pj6RLyb93oDG24cHDph26FbMYRcPrrDTDTM6ghlqgBNXhmc5LGAgayHuTNTHv6guQZiIroibLbAR7fKnl7/vpMDKvnZDafz7laQ7klx0Uwyz2Rpb5nLhdtQ9rNUi7WNCy1ZoG8joWzFyvP04dwKgGCL6C8E2W0lFJffOFFpGBchHA2XZQN3993d1HzZUwzg8QgAKYv0cfJkmDjhv1Xeo8P6kjtDu4e8eRKaa6UiYxlgmLpcQEXuLajolRpmBGtgiycx+6WPAi4W38SwpAPRTYyOSPaYqVbEt3+9nhvF0ZgjRoXUfitvoVl3FO0ck8cwcBAcQaPRYyxrxffdi/enGSKE73lln241I6bxXSzsQ+JIt3A9PljBg2HS00y/JrZrkwhbk4o1O1yWQQdBfLyWJDlhhMxw2wwFXZ45sLeSQEnKrYr4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
